# Generated by Django 2.2.7 on 2019-12-02 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiary', '0003_auto_20191129_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='distance',
        ),
    ]
