# Generated by Django 2.2.7 on 2019-12-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiary', '0004_remove_business_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rate',
        ),
    ]
