# Generated by Django 2.2.7 on 2019-12-02 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiary', '0005_remove_review_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='businesses',
            new_name='business',
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
