# Generated by Django 2.2.7 on 2019-12-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiary', '0008_auto_20191204_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='website',
        ),
    ]
